### ISSUE TITLE
OS X 10.11 support

### ISSUE THREAD

**Issue by zmwangx** [moretension/duti#12]
On OS X 10.11 Public Beta 1 (15A25h):

```
> ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... i386-apple-darwin15.0.0
checking host system type... i386-apple-darwin15.0.0
checking target system type... i386-apple-darwin15.0.0
checking which SDK to use... configure: error: darwin15.0.0 is not a supported system
```

Might need to update the m4 script, just like [what was done for Yosemite](https://github.com/moretension/duti/commit/594dfe0c9d4693afe4dbc23c505764292a48c6b4).

**Comment by vitorgalvao** [comment]
@zmwangx Guessing this can be closed, since https://github.com/moretension/duti/pull/20 was merged.

**Comment by zmwangx** [comment]
Yep, thanks for the notice.
