### ISSUE TITLE
How to undo the association?

### ISSUE THREAD

**Issue by nyngwang** [moretension/duti#22]
I associate my sublime3 with plain-text:

`duti -s com.sublimetext.3 public.plain-text all`.

But now I want to undo it. Please help.

**Comment by nyngwang** [comment]
With `duti -s com.apple.TextEdit public.plain-text all` which solves my problem.

**Comment by BuonOmo** [comment]
I have the same question, shall I open a new issue ? I want to _undo_, not to _overwrite_
