### ISSUE TITLE
support for dotfiles?

### ISSUE THREAD

**Issue by briancrink** [moretension/duti#33]
Is there a case for hidden dotfiles?

**Comment by briancrink** [comment]
found the file type -> `duti -s com.microsoft.VSCode public.unix-executable all`

**Comment by gandalfsaxe** [comment]
@briancrink  Did this also work for `.gitignore`? Did you have to do anything additional to `duti -s com.microsoft.VSCode public.unix-executable all`? It still opens in TextEdit for me (#40)
