### ISSUE TITLE
can't run ./configure command inside project directory ("-bash: ./configure: No such file or directory"), and when running make ("make: *** No targets specified and no makefile found.  Stop.)

### ISSUE THREAD

**Issue by ddd1600** [moretension/duti#5]

**Comment by TGBX** [comment]
Ditto here.

**Comment by moretension** [comment]
Whoa there! Dial down the sense of entitlement, please. No doubt a precompiled binary would be convenient. I'll get to that when I have time. In the meantime, there *is* a homebrew recipe for duti:

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/duti.rb

So you *can* just "brew install duti" and be done.

**Comment by moretension** [comment]
The solution is to run autoconf first:

autoconf
./configure
make
