### ISSUE TITLE
How to reassociate dot files?

### ISSUE THREAD

**Issue by ssbarnea** [moretension/duti#52]
As duti command line interface lacks even a simple `--help` option, trying to find how to reassociate some file types seems to be a real struggle.

I am trying to avoid the apparently implicit TextEdit that is used for opening these:

```
# dot files such:
.gitignore
.yamllint
.flake8
# plain text files without any extension such
COPYING
```

Any hints would be highly appreciated. Thanks

**Comment by iloveitaly** [comment]
Check out my dotfiles for some examples:

https://github.com/iloveitaly/dotfiles/blob/ea2e0bf0231f69f9a1bcb0b10087e46c422b18d9/duti#L15

**Comment by ssbarnea** [comment]
While that example was not able help me I figured it out from another comment:
```
duti -s com.microsoft.VSCode public.data all
```
Basically most of the files without an extension are considered to be `public.data`
